[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

evm_version="cancun"
solc_version="0.8.26"

# =============================================================================
# FORK TESTING CONFIGURATION
# =============================================================================

# RPC endpoints for different networks
[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
base = "${BASE_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

# Fork testing configuration
[profile.fork]
url = "${FORK_URL}"
# block_number = 18500000  # Uncomment and set specific block if needed

# Etherscan API keys for contract verification
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
polygon = { key = "${ETHERSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
optimism = { key = "${ETHERSCAN_API_KEY}", url = "https://api-optimistic.etherscan.io/api" }